### ISSUE TITLE
Unstake insufficient balance error while I have balance

### ISSUE THREAD

**Issue by jasperjansz** [arkadiko-dao/arkadiko#31]
I staked 1 DIKO and then tried to unstake 0.5 DIKO. I get an error that I have insufficient balance: https://explorer.stacks.co/txid/0x26e87336401874e2020466525de5ec0a14807ad57ed0f3b4c2087372267b6c7b?chain=testnet.

It seems to me I do have the balance: 
![image](https://user-images.githubusercontent.com/25477905/122372460-f9d18500-cf60-11eb-8c8e-6913c272258d.png)

**Comment by philipdesmedt** [comment]
Thanks for reporting!

In the transaction, it shows you tried unstaking 0 DIKO (see amount under arguments on https://explorer.stacks.co/txid/0x26e87336401874e2020466525de5ec0a14807ad57ed0f3b4c2087372267b6c7b?chain=testnet).. possibly you used 0,5 instead of 0.5 (or the other way around, not sure what the decimal sign is)?

**Comment by philipdesmedt** [comment]
@jasperjansz thoughts on my above comment?

**Comment by philipdesmedt** [comment]
Figured out what was wrong. Fixed on commit in master. Thanks @jasperjansz
