### ISSUE TITLE
something wrong with Swap Contract?

### ISSUE THREAD

**Issue by nighttimeBIT** [arkadiko-dao/arkadiko#424]
Web Wallet warns me that approving this tx (Swap) allows the Contract to drain all my funds. 

is there any Explanation for this? Maybe a bug in the Code?

**Comment by 314159265359879** [comment]
That warning shows up when the dapp tries to send a transaction with post conditions in allow mode. If you trust the contracts that are being called you can still do this safely. Sending with post conditions in deny mode is preferred/safer because in that case any transfers will be specified and they can never exceed those specified conditions.

**Comment by philipdesmedt** [comment]
We have an issue open to implement post conditions on the swap (and in some other places that are still needed), see #426 - You can track progress there. I will close this one in the meantime.
