### ISSUE TITLE
Same lot shows twice

### ISSUE THREAD

**Issue by nieldeckx** [arkadiko-dao/arkadiko#58]
<img width="1141" alt="Screenshot 2021-06-20 at 17 48 07" src="https://user-images.githubusercontent.com/5592676/122680489-b3458a00-d1ef-11eb-9125-7030a1e26810.png">

**Comment by 314159265359879** [comment]
![image](https://user-images.githubusercontent.com/33360391/122687018-82c41700-d214-11eb-9791-3e1f0d4db228.png)
Did some more research on this. 
When I pay the full price twice, one transaction simply fails ([1](https://explorer.stacks.co/txid/0xf19152482e19654a202d99aa1df2d1cdd8bcae87ffde40b7df6d868952bdc9aa?chain=testnet), [2](https://explorer.stacks.co/txid/0xc20137b93fa16110ec42d069208e1089cb475c8e0431c5f9e2b985112ad0bd66?chain=testnet)). That is what I would expect. 
When I bid 2 xUSD first and 117 xUSD (full price) second... that is when this happens. Showing same lot twice.
[Bid 1 2 xUSD](https://explorer.stacks.co/txid/0x68f1d7fd08cbcc3c5fd09138b94095f9ae63b2ccd84d57dcfd1c3e4e1e2fac9a?chain=testnet) 
[Bid 2 117 xUSD](https://explorer.stacks.co/txid/0x7eabf2e5e2ec72f1a240e49709a09e9fd60e6abbb2d3e452519304afae13db2e?chain=testnet) 

Since in this case I am bidding 119 xUSD on the lot it would make more sense to add those numbers and have one instance with 119. First time this happened to me I just made the mistake of bidding twice on the same lot, that is less likely to happen on mainnet.
I can see people making a mistake and then outbidding themselves by bidding again. It would make sense if that is "added" to the bid for the lot, right?
